# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 13:46
from __future__ import unicode_literals

import childf_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HamYar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(childf_app.models.HasUserMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MadadJou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(childf_app.models.HasUserMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MadadKar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(childf_app.models.HasUserMixin, models.Model),
        ),
    ]
