# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 11:57
from __future__ import unicode_literals

import childf_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HamYar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_melli', models.CharField(max_length=10, unique=True)),
                ('activation_code', models.CharField(default=childf_app.models.random_string, max_length=6)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('1', 'مذکر'), ('2', 'مونث')], default='1', max_length=2)),
                ('education', models.CharField(choices=[('1', 'بی\u200cسواد'), ('2', 'ابتدایی'), ('3', 'دیپلم'), ('4', 'لیسانس'), ('5', 'فوق\u200cلیسانس'), ('6', 'دکترا')], default='1', max_length=2)),
                ('payment_period', models.IntegerField(blank=True, choices=[(1, '۱ ماهه'), (2, '۲ ماهه'), (3, '۳ ماهه'), (4, '۴ ماهه')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hamyar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MadadJou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(childf_app.models.HasUserMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MadadKar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(childf_app.models.HasUserMixin, models.Model),
        ),
    ]
