# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madadjou',
            name='code_melli',
        ),
        migrations.AddField(
            model_name='madadjou',
            name='bimari',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='bimari_madar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='bimari_pedar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='birth_date_madar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='birth_date_pedar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='daramad_madar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='daramad_pedar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='ejare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='elat_fot_madar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='elat_fot_pedar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='gender',
            field=models.CharField(choices=[('1', 'مذکر'), ('2', 'مونث')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='ghaiem_feli',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='mahal_sokunat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='malekiat_maskan',
            field=models.CharField(choices=[('1', 'دارد'), ('2', 'ندارد')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='manbae_komake_digar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='meghdar_komake_digar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='niaz_avalie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='niaz_mahane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='picture',
            field=models.ImageField(default=1, upload_to='madadju'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='madadjou',
            name='sharaiet_jesmani',
            field=models.CharField(choices=[('1', 'سالم'), ('2', 'معلول')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='shoghl_madar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='shoghl_pedar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='shomare_parvande',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tahsilat_madar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tahsilat_pedar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tarighe_komake_digar',
            field=models.CharField(choices=[('1', 'دارد'), ('2', 'ندارد')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tedad_baradaran',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tedad_khaharan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tedad_otagh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='tozihat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='vaziat_eshteghal_pedar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='vaziat_jesmani_madar',
            field=models.CharField(choices=[('1', 'سالم'), ('2', 'معلول')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='vaziat_jesmani_pedar',
            field=models.CharField(choices=[('1', 'سالم'), ('2', 'معلول')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='vaziat_omumi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='madadjou',
            name='vaziat_sokunat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
