# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar',
            name='code_melli',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hamyar',
            name='payment_period',
            field=models.IntegerField(blank=True, choices=[(1, '۱ ماهه'), (2, '۲ ماهه'), (3, '۳ ماهه'), (6, '۶ ماهه')], null=True),
        ),
    ]
