# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childf_app', '0002_auto_20180205_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadjou',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='madadju'),
        ),
    ]
