# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 13:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('childf_app', '0003_auto_20180205_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('critical', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MadadPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='childf_app.HelpRequest')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='madadjupayment',
            name='madadju',
        ),
        migrations.RemoveField(
            model_name='madadjupayment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='madadjou',
            name='niaz_avalie',
        ),
        migrations.AddField(
            model_name='madadjou',
            name='last_periodic_request_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='madadjou',
            name='niaz_mahane',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MadadjuPayment',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='madadjou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='childf_app.MadadJou'),
        ),
    ]
