# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childf_app', '0004_auto_20180205_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyar',
            name='supported_children',
            field=models.ManyToManyField(related_name='hamian', to='childf_app.MadadJou'),
        ),
    ]
